<a href="https://colab.research.google.com/github/imnishu07/TensorFlow_Lite_Projects/blob/basicProjects/Project1_Intro_to_Keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Step 1: Setting up Tensorflow
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.18.0


In [2]:
#Step 2: Loading a dataset
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 1s 0us/step


In [3]:
#Step 3.0: Building a machine learning model
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

/usr/local/lib/python3.11/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [4]:
#Step 3.1: The model returns a vector of logits or log-odds scores for each class
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.63359356, -0.06274694, -0.04759286, -0.6746201 ,  0.16200072,
        -0.06424706, -0.47929844, -0.0087942 , -0.80176806, -0.7084069 ]],
      dtype=float32)

In [5]:
#Step 3.2: The following function converts these logits to probabilities for each class
tf.nn.softmax(predictions).numpy()


array([[0.21050929, 0.10491906, 0.10652112, 0.05690118, 0.13135938,
        0.10476179, 0.06917487, 0.11073523, 0.05010737, 0.05501079]],
      dtype=float32)

In [6]:
#Step 3.3: Defining a loss function for training
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [7]:
#Step 3.4: Modifying loss funtion for initial values
loss_fn(y_train[:1], predictions).numpy()

np.float32(2.256066)

In [8]:
#Step 3.5: Set optimizer, loss function and metrics
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [9]:
#Step 4.0: Train the model
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - accuracy: 0.8605 - loss: 0.4860
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - accuracy: 0.9561 - loss: 0.1505
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9674 - loss: 0.1056
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9731 - loss: 0.0886
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - accuracy: 0.9768 - loss: 0.0760


In [10]:
#Step 4.1: Evaluate the model
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - 3ms/step - accuracy: 0.9785 - loss: 0.0712


[0.07116284966468811, 0.9785000085830688]

In [11]:
#Step 4.2: Wrapping the trained model to return a probability
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [12]:
#Step 4.3: Taking the first 5 examples from the test set to pass through the probability model
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[5.7759415e-08, 1.6857324e-09, 4.7994174e-05, 7.9653248e-05,
        4.8580563e-11, 1.7988258e-07, 1.5961784e-12, 9.9987161e-01,
        2.0315692e-07, 2.8965326e-07],
       [9.0809946e-09, 3.7911796e-05, 9.9988174e-01, 7.9882208e-05,
        1.2176866e-15, 1.1531929e-07, 1.3192680e-07, 2.3198215e-14,
        2.4582522e-07, 3.3104714e-14],
       [4.6019275e-07, 9.9695009e-01, 3.2365997e-04, 3.8959075e-05,
        4.5774103e-04, 5.5805231e-05, 2.5646756e-05, 1.8112747e-03,
        3.2156045e-04, 1.4807094e-05],
       [9.9999499e-01, 9.9878572e-10, 4.9181989e-07, 2.5684942e-08,
        7.0369595e-08, 9.9065879e-08, 4.1138160e-06, 1.1366975e-07,
        6.5069128e-10, 4.1324540e-08],
       [4.1847041e-05, 6.9395574e-09, 1.3478472e-06, 3.8797989e-08,
        9.9828303e-01, 6.1480055e-06, 2.5374302e-05, 1.2628846e-04,
        1.3338806e-06, 1.5145461e-03]], dtype=float32)>

In [13]:
#Conclusion: We have trained a machine learning model using a prebuilt dataset using the Keras API